apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ai-demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-l7hfb-1.apps.cluster-l7hfb.dynamic2.redhatworkshops.io/tssc/ai-demo-app:b280864b5ae0a49709fb7046b933fc5f8d982d34@sha256:ed2ad6ab1a2405e0753570f2b82e32f62591140186ceeb57cd705b252420882b
          name: container-image
