apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ai-demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-892bb-1.apps.cluster-892bb.dynamic.redhatworkshops.io/tssc/ai-demo-app:2d36f90190bc94f2859d948da40434da7c187c8c@sha256:70ac411425692990e5a8d4a9380d4d79d1703effed3f03b81893d66ccf8d171c
          name: container-image
