apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ai-demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay-892bb-1.apps.cluster-892bb.dynamic.redhatworkshops.io/tssc/ai-demo-app:8c6fa2516ddf6382a26765e7120e004f8c205d44@sha256:b56f438ff48233b2fdc4f33cd9611e0a34b4b9b2bfc2c0fef0e6d8e13edae140
          name: container-image
