apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: ai-demo-app
  janus-idp.io/tekton: ai-demo-app
  backstage.io/kubernetes-id: ai-demo-app
  backstage.io/kubernetes-namespace: tssc-app
  app.kubernetes.io/part-of: ai-demo-app
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
