apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ai-demo-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ai-demo-app
  name: ai-demo-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ai-demo-app
